### ISSUE TITLE
Please remember to increase versionCode

### ISSUE THREAD

**Issue by IzzySoft** [danopdev/Perspective#1]
Though there are already multiple releases available, the latest APK still identifies with `versionCode: 1`:

    package: name='com.dan.perspective' versionCode='1' versionName='1.6'

This is a problem, as Android uses this to tell versions apart and decide which one is newer. May I suggest to [increase it](https://github.com/danopdev/Perspective/blob/master/app/build.gradle#L29) to `3` for the next release, and then increment on each new release? Thanks in advance!

**Comment by danopdev** [comment]
You are right. I only change versionName, but maybe this is a bad practice.
I will update it for the next release.

**Comment by IzzySoft** [comment]
Wonderful, thanks! As a bonus point, that will make automated updates possible. Find [your app here](https://apt.izzysoft.de/fdroid/index/apk/com.dan.perspective) in my repo with is quite popular among F-Droid users. And be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme :smiley:

PS: If you want, I can offer you a PR with the app description etc. in [Fastlane structure](https://gitlab.com/-/snippets/1895688) so you can easily adjust it to your likings; it would then be cross-checked and changes pulled along with each new release you make. Just let me know.

**Comment by danopdev** [comment]
Do I need to generate a new build with the version code updated ?

About Fastlane structure: can I  have shared content with "README.md" ? If I don't have to update 2 files for screenshots, explanations ... I'm perfectly OK with it.

**Comment by IzzySoft** [comment]
> Do I need to generate a new build with the version code updated ?

I'd say the past is gone and only few people with special cases will be interested in previous versions – so it should be sufficient when you start increasing with the next release, making sure new releases have a proper `versionCode`.

As for Fastlane/Readme: Of course you can use the Fastlane screenshots in your Readme directly, to avoid duplication. Just the description will be a bit difficult to "share" between the two, as the Readme usually has a different structure (and purpose) than the app description. You probably could copy-paste the Fastlane description to make it part of the Readme, but that might a bit tricky to due to formatting. That said, how often do you suppose you'll have to change the app description? Probably won't happen that often, so it won't be that much "overhead" – small as it is at that with its 2 paragraphs :wink:

**Comment by danopdev** [comment]
OK, let's give it a try. Please make the PR.

**Comment by IzzySoft** [comment]
PR opened. I also added German summary & description.

**Comment by danopdev** [comment]
VersionCode is incressed for the next release.

**Comment by IzzySoft** [comment]
Thanks! Fastlane will be checked with the next release, too (thanks for merging!).
